services:
  mongo:
    image: mongo:6
    container_name: edubook-mongo
    restart: always
    volumes:
      - mongo-data:/data/db

  backend:
    image: kavi2001/edubook-backend:latest
    container_name: edubook-backend
    restart: always
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/edubook
      - PORT=5000
    depends_on:
      - mongo

  frontend:
    image: kavi2001/edubook-frontend:latest
    container_name: edubook-frontend
    restart: always
    ports:
      - "80:80"
    depends_on:
      - backend

volumes:
  mongo-data:


